{% set name = "celery-singleton" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e359936f3e4ad57cda567727ce1144c137e20fc95b3a4f8e82d21b9fd1f5a53e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6
  run:
    - python >=3.6
    - celery >=4
    - redis-py

test:
  imports:
    - celery_singleton

about:
  home: https://github.com/steinitzu/celery-singleton
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Prevent duplicate celery tasks
  description: |
    Duplicate tasks clogging up your message broker?
    Do time based rate limits make you feel icky? Look no further!
    This is a baseclass for celery tasks that ensures only one instance of
    the task can be queued or running at any given time.
    Uses the task's name+arguments to determine uniqueness.

extra:
  recipe-maintainers:
    - duncanmmacleod
