travis:
  secure:
    BINSTAR_TOKEN: gsWsnARSPwKVBpkkKBdNqwVTxbj/v4q9SN6uFN3nYwvOk6gjpLlpRBW/1N48xRzzQMhfH3W8PJngIj3exxjb6I7+7ChE309xhlcL8sscaH4WgRpgdYD0bNGyHWLyfTb8PbI6gW5qaWyOpYw/6pep7dHbzsLcBTxm9RmIokw0GKqIlerGFz3VyNIGTXRrdLHG9/k8fbmPr1HD/3bV0dXxW/jakV8d+onHcJmHKIF56wl5s4tOIiGXYKETsn8Kmj6BUoQ4dUxdzSbmFLHh7W2s8iLhtFlFbtXT+6Bmi7PJy1KuOKsGBZRvcLjohPNkljk6vypJ/yEgKaGADAhyTekcMY8Gh7j8vqZVMMFYCYShTBrrMa54GsEWvUDe6hBiPsA3bXLJlW7iOAKkdu80ioNzhDQAWaPjmRux9irEleynhT2deQFUrR1Y1lBkdblCOw5sl/GA6TgpN7IaYwW/SsjPVb0mUwyKlHlR7F8qOfwFPVhRflbp+LlRHbGCeYVamW78u7QclmAYiHjVsyqfvMIvyWLFfHExIOK4TrURgioHrRjz8xEc0ZtILoBDtAanxXbH/FzGTMDxOvW1pS2uAiluOrHDahrgtDzEP0rUAwVRdvxLER6RhlRp7TFgG5CG1t4LR7xJKjXyLs5rdU/LIUM74cTlEzMc64aiwfn2DAgZw1w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
